# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60dc2fbb4ab48683496ba86820be885ffa887f8073edaaa459043de3952ddec7056a4db90af12d450d95864366974e8a11e21538f70eabe8e0e7aa98d74d366c

test:
  secret_key_base: c1d073c0d52f853a9b701d7ae70ddb4789af1522b9501749137d22e6755a978213d7cbdd6a0017b5d8c59427dfdd920c86790baf808e06c81e49034bbd5af67f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
